name: Build and push to Docker Hub

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to Docker Hub
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build the image
      run: |
        docker build --push \
          --tag thijsputman/tc66c-mqtt:latest \
          --platform linux/arm64 .
