name: Release

on:
  release:
    types: [published]

jobs:
  tag_docker_hub:
    name: Tag release on Docker Hub
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag Docker image
        run: |
          ref=(${GITHUB_REF//\// })
          tag=${ref[2]}
          if [[ ${tag:0:1} == "v" ]] ; then
            tag=${tag:1}
          fi
          docker tag thijsputman/tc66c-mqtt:"${GITHUB_SHA:0:7}" \
            thijsputman/tc66c-mqtt:"$tag"
